spring:
  application:
    name: lm-oauth
  datasource:
    url: jdbc:postgresql://localhost:5433/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: https://lm-oauth.cartagenacorporation.com/login/oauth2/code/google
server:
  port: 8081
app:
  oauth2:
    redirect-url: http://tu-frontend-url/oauth2/redirect
  cors:
    allowed-origins: https://cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
    expiration: '900000'
    refreshExpiration: '604800000'
role:
  service:
    url: https://lm-users.cartagenacorporation.com/api/roles
